title: Getting to know GitHub Pages
author: Alassane NIANG
email: your-email@domain.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  I'm thrill to share with you my learning experience of GitHub Pages.
  Stay with me

# social links
twitter_username: adniang75 # DO NOT include the @ character, or else the build will fail!
github_username:  adniang75 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
